### ISSUE TITLE
drawings don't show up when you go from one image and then back again

### ISSUE THREAD

**Issue by gracemcl** [loganfred/gladlab-ip#3]
[export (1).json.zip](https://github.com/loganfred/gladlab-ip/files/7672426/export.1.json.zip)

**Comment by loganfred** [comment]
My best guess is that this broke during refactoring. There's even a commit that references fixing this issue.

I fixed it by filtering the list of paths after the `update` button is clicked to only the current selection, then adding those paths to the canvas. Refer to the commit for the diff.
