### ISSUE TITLE
postprocess- want to export a subset of channels

### ISSUE THREAD

**Issue by gracemcl** [loganfred/gladlab-ip#6]
Could you add an option to specify which channels to create the cropped images of? (for example, channels 1 and 2 but not channel 0)

**Comment by loganfred** [comment]
In addition to the `--all-channels` argument  there is now a `--channels` argument which permits at least one space-separated int.

For example, the following command would output the 1 and 0 channels (in that order).

```shell
python main.py postprocess ~/Downloads/export.json -c 1 0 -d ~/Desktop/test -v
```
